"""Doubles a 1-bit icon header to twice its size.

The home menu draws its icons at 64px, and the artwork in this directory is
32px. This is a nearest-neighbour 2x of the existing bitmap - each pixel
becomes a 2x2 block - so the glyphs keep the family they were drawn in while
larger art is being made. It is not a substitute for drawing at 64px: strokes
come out twice as thick and diagonals stay as jagged as they were.

Scaling commutes with the 90-degree rotation the icons are stored in, so the
stored bytes can be doubled directly without unrotating first.

Usage: python scripts/upscale_icon.py src/components/icons/tasks.h TasksIcon Tasks64Icon 32
"""

import re
import sys

USAGE = "Usage: python scripts/upscale_icon.py input.h SourceArrayName OutputArrayName size"


def read_bitmap(path, array_name, size):
    text = open(path, encoding="utf-8").read()
    start = text.index(array_name)
    body = text[text.index("{", start) + 1 : text.index("}", start)]
    values = [int(v, 16) for v in re.findall(r"0x[0-9A-Fa-f]{2}", body)]
    expected = size * size // 8
    if len(values) != expected:
        raise SystemExit(f"{array_name}: got {len(values)} bytes, expected {expected} for {size}x{size}")
    return values


def double(values, size):
    row_bytes = size // 8
    out = []
    for row in range(size):
        bits = []
        for byte in values[row * row_bytes : (row + 1) * row_bytes]:
            for bit in range(7, -1, -1):
                pixel = (byte >> bit) & 1
                bits.extend((pixel, pixel))
        doubled_row = []
        for i in range(0, len(bits), 8):
            byte = 0
            for bit in bits[i : i + 8]:
                byte = (byte << 1) | bit
            doubled_row.append(byte)
        # Each source row becomes two identical rows.
        out.extend(doubled_row)
        out.extend(doubled_row)
    return out


def main():
    if len(sys.argv) != 5:
        raise SystemExit(USAGE)
    path, source_name, output_name, size = sys.argv[1], sys.argv[2], sys.argv[3], int(sys.argv[4])

    doubled = double(read_bitmap(path, source_name, size), size)
    out_size = size * 2

    lines = []
    for i in range(0, len(doubled), 19):
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in doubled[i : i + 19]) + ",")
    # clang-format keeps the closing brace on the last data line, so emit it
    # that way: CI runs bin/clang-format-fix over the whole tree and fails on a
    # diff, and generated files are checked in.
    body = "\n".join(lines).rstrip(",")

    print(f"#pragma once")
    print(f"#include <cstdint>")
    print()
    print(f"// size: {out_size}x{out_size}")
    print(f"// Nearest-neighbour 2x of {source_name} ({size}x{size}), generated by")
    print(f"// scripts/upscale_icon.py. Stored pre-rotated 90 degrees like every other")
    print(f"// icon here; see tasks.h for why.")
    print(f"static const uint8_t {output_name}[] = {{")
    print(body + "};")


if __name__ == "__main__":
    main()
